# Site Settings
locale: "en-US"
title: "Donghyuk Shin"
title_separator: "|"
name: "Donghyuk Shin"
description: "Ph.D. Student in Information Security at Chonnam National University"
url: "https://soledo.github.io"
baseurl: ""
repository: "soledo/soledo.github.io"

# Site Author
author:
  name: "Donghyuk Shin"
  avatar: "/images/avatar.jpg"
  bio: "Ph.D. Student in Information Security"
  location: "Gwangju, South Korea"
  employer: "Chonnam National University"
  email: "shindh2@jnu.ac.kr"
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "soledo"
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin: "shindh2"
  orcid: "0000-0002-2384-3380"
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
  googlescholar:

# Research Interests
research_interests:
  - Cyber Threat Intelligence
  - Cyber Physical System
  - Threat Modeling
  - Digital Forensics
  - Cyber Deception

# Resume Settings (for /cv-print/ page)
resume_avatar: "true"
resume_name: "Donghyuk Shin"
resume_title: "Ph.D. Candidate, System Security Research Center"
resume_contact_email: "shindh2@jnu.ac.kr"
resume_contact_telephone: "(+82) 010-8967-1014"
resume_contact_address: "#415, College of AI Convergence, Chonnam National University, Gwangju, Korea"
resume_header_contact_info: "#415, College of AI Convergence, Chonnam National University, Gwangju, Korea<br>E-mail: shindh2@jnu.ac.kr"
display_header_contact_info: "true"
resume_header_intro: "<p>Cyber Threat Intelligence, Cyber Physical System, Threat Modeling, Digital Forensics, Cyber Deception</p>"
resume_looking_for_work: "yes"
resume_section_experience: true
resume_section_education: true
resume_section_license: true
resume_section_recognition: true
resume_social_links:
  resume_github_url: "https://github.com/soledo"
  resume_linkedin_url: "https://www.linkedin.com/in/shindh2"
  resume_website_url: "http://ssrc.jnu.ac.kr"
resume_print_social_links: true
resume_theme: default

# Build Settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Seoul

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: /page:num/

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true

# Include _pages folder
include:
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - Dockerfile
  - .travis.yml
